# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: people.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cpeople.proto\"\xb8\x01\n\x06Person\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x11\n\tfirstName\x18\x02 \x01(\t\x12\x10\n\x08lastName\x18\x03 \x01(\t\x12\x0f\n\x07isAlive\x18\x04 \x01(\x08\x12\x0b\n\x03\x61ge\x18\x05 \x01(\x05\x12\x19\n\x07\x61\x64\x64ress\x18\x06 \x01(\x0b\x32\x08.Address\x12\"\n\x0cphoneNumbers\x18\x07 \x03(\x0b\x32\x0c.PhoneNumber\x12\x10\n\x08\x63hildren\x18\x08 \x03(\t\x12\x0e\n\x06spouse\x18\t \x01(\t\"Q\n\x07\x41\x64\x64ress\x12\x15\n\rstreetAddress\x18\x01 \x01(\t\x12\x0c\n\x04\x63ity\x18\x02 \x01(\t\x12\r\n\x05state\x18\x03 \x01(\t\x12\x12\n\npostalCode\x18\x04 \x01(\t\"+\n\x0bPhoneNumber\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0e\n\x06number\x18\x02 \x01(\t\"\x12\n\x10GetPeopleRequest\",\n\x11GetPeopleResponse\x12\x17\n\x06people\x18\x01 \x03(\x0b\x32\x07.Person\"\x1e\n\x10GetPersonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"+\n\x10\x41\x64\x64PersonRequest\x12\x17\n\x06person\x18\x01 \x01(\x0b\x32\x07.Person\"$\n\x11\x41\x64\x64PersonResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\":\n\x13UpdatePersonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x17\n\x06person\x18\x02 \x01(\x0b\x32\x07.Person\"\'\n\x14UpdatePersonResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"!\n\x13\x44\x65letePersonRequest\x12\n\n\x02id\x18\x01 \x01(\x05\"\'\n\x14\x44\x65letePersonResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\x9a\x02\n\rPeopleService\x12\x32\n\tGetPeople\x12\x11.GetPeopleRequest\x1a\x12.GetPeopleResponse\x12\'\n\tGetPerson\x12\x11.GetPersonRequest\x1a\x07.Person\x12\x32\n\tAddPerson\x12\x11.AddPersonRequest\x1a\x12.AddPersonResponse\x12;\n\x0cUpdatePerson\x12\x14.UpdatePersonRequest\x1a\x15.UpdatePersonResponse\x12;\n\x0c\x44\x65letePerson\x12\x14.DeletePersonRequest\x1a\x15.DeletePersonResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'people_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_PERSON']._serialized_start=17
  _globals['_PERSON']._serialized_end=201
  _globals['_ADDRESS']._serialized_start=203
  _globals['_ADDRESS']._serialized_end=284
  _globals['_PHONENUMBER']._serialized_start=286
  _globals['_PHONENUMBER']._serialized_end=329
  _globals['_GETPEOPLEREQUEST']._serialized_start=331
  _globals['_GETPEOPLEREQUEST']._serialized_end=349
  _globals['_GETPEOPLERESPONSE']._serialized_start=351
  _globals['_GETPEOPLERESPONSE']._serialized_end=395
  _globals['_GETPERSONREQUEST']._serialized_start=397
  _globals['_GETPERSONREQUEST']._serialized_end=427
  _globals['_ADDPERSONREQUEST']._serialized_start=429
  _globals['_ADDPERSONREQUEST']._serialized_end=472
  _globals['_ADDPERSONRESPONSE']._serialized_start=474
  _globals['_ADDPERSONRESPONSE']._serialized_end=510
  _globals['_UPDATEPERSONREQUEST']._serialized_start=512
  _globals['_UPDATEPERSONREQUEST']._serialized_end=570
  _globals['_UPDATEPERSONRESPONSE']._serialized_start=572
  _globals['_UPDATEPERSONRESPONSE']._serialized_end=611
  _globals['_DELETEPERSONREQUEST']._serialized_start=613
  _globals['_DELETEPERSONREQUEST']._serialized_end=646
  _globals['_DELETEPERSONRESPONSE']._serialized_start=648
  _globals['_DELETEPERSONRESPONSE']._serialized_end=687
  _globals['_PEOPLESERVICE']._serialized_start=690
  _globals['_PEOPLESERVICE']._serialized_end=972
# @@protoc_insertion_point(module_scope)
